bash: Style
Signed-off-by: Mario Alfredo Carrillo Arevalo <mario.alfredo.c.arevalo@intel.com>

diff --git a/bash/07-special-vars b/bash/07-special-vars
--- a/bash/07-special-vars
+++ b/bash/07-special-vars
@@ -1,12 +1,10 @@
 #!/bin/bash
 
-# [$#] var contains the number of arguments
-# that has been received
+# [$#] var contains the number of arguments that has been received.
 if (( $# > 0 ));
 then
 
-	# [$@] var contains all arguments
-	# written bv the user as parameters
+	# [$@] var contains all arguments written bv the user as parameters
 	echo "Arguments received: $#"
 	for ARG in $@
 	do
@@ -15,25 +13,24 @@ then
 
 	# [$*] var contains all argumets
 	# The difference between $@ and $* is:
-	# [$@] is equivalent: "$1" "$2" "$3" ...
-	# [$*] is equivalent: "$1 $2 $3"
+	#
+	# 	[$@] is equivalent: "$1" "$2" "$3" ...
+	# 	[$*] is equivalent: "$1 $2 $3"
 	echo "The argument received were: $*"
 	echo "The first argument was: $1"
 
-	# [$!] var contains the PID (process
-	# identifier) of the most recently command
-	# executed in background in this bash session.
+	# [$!] var contains the PID (process identifier) of the most
+	# recently command executed in background in this bash session.
 	uname -r &
 	echo "PID of last bg command: $!"
 
-	# [$$] var contains the PID (process
-	# identifier) of the most recently command
-	# executed in this bash session.
+	# [$$] var contains the PID (process identifier) of the most
+	# recently command executed in this bash session.
 	uname -a
 	echo "PID of last command: $$"
 
-	# [$?] var contains the exit status of the most
-	# recently executed foreground pipeline.
+	# [$?] var contains the exit status of the most recently executed
+	# foreground pipeline.
 	uname -s
 	echo "Exit code $?"
 
